#!/usr/bin/env bash
# copy file from local machine to server

if  (("$#" < "3"))
   then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 31
fi

scp -i "$4" "$1" "$3"@"$2":~/
