#!/usr/bin/env bash
# create a 404 redirect error

redirect="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
error="\terror_page 404 /not_found.html;"

apt-get update
apt install nginx -y
echo  "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > not_found.html
sed -i "/server_name _;/a\ ${redirect}" /etc/nginx/sites-available/default
sed -i "/server_name _;/a\ ${error}" /etc/nginx/sites-available/default
service nginx start
