#!/usr/bin/env bash
# install load balancer and configure it

apt-get update -y
apt-get install haproxy -y

frontend_config="\nfrontend myfrontend\n\tmode http\n\tbind *:80\n\toption forwardfor\n\tdefault_backend mybackend\n"
backend_config="\n\nbackend mybackend\n\tbalance roundrobin\n\tserver 177000-web-01 34.205.65.154:80 check cookie web-01\n\tserver 177000-web-02 34.239.107.150:80 check cookie web-02"

echo -e "$frontend_config" >> /etc/haproxy/haproxy.cfg
echo -e "$backend_config" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy

if (( "$(pgrep -c haproxy)" <= "0"))
then
    service haproxy start
else
    service haproxy restart
fi
