#!/usr/bin/env bash
install load balancer and configure it
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.6 -y
apt-get update -y
apt-get install haproxy=2.6.\* -y

frontend_config="\nfrontend myfrontend\n\tmode http\n\tbind *:80\n\tdefault_backend mybackend\n"
backend_config="\n\nbackend mybackend\n\tbalance roundrobin\n\tserver web1 34.205.65.154\n\tserver web2 34.239.107.150"

echo -e "$frontend_config" >> /etc/haproxy/haproxy.cfg
echo -e "$backend_config" >> /etc/haproxy/haproxy.cfg

echo -e "ENABLED=1" >> /etc/default/haproxy

if (( "$(pgrep -c haproxy)" <= "0"))
then
    service haproxy start
else
    service haproxy start
fi
