#!/usr/bin/env bash
# create backup of database

if [[ "$#" -ne "1" ]]
then
   exit
fi

# sql dump to get sql script that will create the entire database when run
sudo mysqldumb -u root -p "$1" --all-databases | sudo tee backup.sql

# compress the file
tar cavf "$(date +"%d-%m-%y".tar.gz)" backup.sql
