#!/usr/bin/env bash
# kill nginx process and create a proper simlink, then start the service
pkill nginx | sed "s/-p \$PID/-p -100/"
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default -f
service nginx restart
