#!/usr/bin/env bash
# process manager

function start ()
{
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    echo "manage_my_process started"
    
}
function stop ()
{
    xargs kill < /var/run/my_process.pid
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}
function restart(){
    xargs kill < /var/run/my_process.pid
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo $! >> /var/run/my_process.pid
    echo "manage_my_process restarted"
}

case $1 in
    "start")
        start
    ;;
    "stop")
        stop
    ;;
    "restart")
        restart
        ;;
    *)
    echo "Usage: manage_your_process {start|stop|restart}"
    ;;
esac
