#!/usr/bin/env bash
#IFS STORY

while IFS=: read -r USERNAME PASSWORD USERID GROUP_ID UIDINFO HOME_DIRECTORY COMMAND_SHELL
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USERID place is protected by the passcode $PASSWORD, more info about the user here: $UIDINFO"
done < /etc/passwd
