#!/usr/bin/env bash
#for loop wiht if statement for best school
i=0
while (( i <= 10));
do
    
    if ((i == 9));
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
