#!/usr/bin/env bash
#file checker

fn="school"

if [ -e $fn ];
then
    echo "school file exists"
    
    if [ ! -s "$fn" ];
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    
    if [ -f $fn ];
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
