#!/usr/bin/env bash
# changing the home ip

cp /etc/hosts ~/hosts.new
sed -i s/^127\.0\.0\.1/127.0.0.2/ ~/hosts.new
printf "#custom host\n8.8.8.8\tfacebook.com" >> ~/hosts.new
cat ~/hosts.new
cp -f ~/hosts.new /etc/hosts
